### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by ghost** [jocephus/WikiLeaker#1]
This error occurs when running setup.sh on default installations of Kali as well as after installing Recon-ng from source (whether or not Recon-ng is installed as root):

`cp: cannot create regular file '/root/.recon-ng/modules/recon/domains-contacts/wikileaker.py': No such file or directory`

**Comment by jocephus** [comment]
Deleted that line of the script since WikiLeaker is now in the Recon-ng marketplace.
